=== KotofeyG/Task2/test_resources/testSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="urn:com.kotov.greenhouse"
        xmlns:tns="urn:com.kotov.greenhouse"
        elementFormDefault="qualified">

    <element name="flowers" type="tns:Flowers"/>
    <element name="flower" type="tns:Flower"/>
    <element name="cut-flower" type="tns:CutFlower" substitutionGroup="tns:flower"/>
    <element name="indoor-flower" type="tns:IndoorFlower" substitutionGroup="tns:flower"/>

    <complexType name="Flowers">
        <sequence>
            <element ref="tns:flower" minOccurs="6" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Flower" abstract="true">
        <sequence>
            <element name="title" type="tns:Title"/>
            <element name="origin" type="tns:Origin"/>
            <element name="petal-color" type="tns:Color"/>
        </sequence>
        <attribute name="vendor-code" type="tns:VendorCode" use="required"/>
        <attribute name="planting-date" type="date" use="required"/>
    </complexType>

    <complexType name="CutFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="stem-length" type="tns:StemLength"/>
                    <element name="bud-state" type="tns:BudState"/>
                </sequence>
                <attribute name="cut-date" type="date" use="required"/>
                <attribute name="leaves" type="boolean" use="optional" default="true"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="IndoorFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="pot-type" type="tns:PotType"/>
                    <element name="soil" type="tns:Soil"/>
                    <element name="watering" type="tns:Watering"/>
                    <element name="average-temperature" type="tns:Temperature"/>
                    <element name="photophilous" type="boolean"/>
                    <element name="multiplying" type="tns:Multiplying"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Watering">
        <restriction base="int">
            <minInclusive value="50"/>
            <maxInclusive value="2000"/>
        </restriction>
    </simpleType>

    <simpleType name="Temperature">
        <restriction base="double">
            <minInclusive value="10"/>
            <maxInclusive value="35"/>
        </restriction>
    </simpleType>

    <simpleType name="StemLength">
        <restriction base="int">
            <minInclusive value="25"/>
            <maxInclusive value="75"/>
        </restriction>
    </simpleType>

    <simpleType name="Title">
        <restriction base="string">
            <pattern value="[a-zA-Z ]{1,35}"/>
        </restriction>
    </simpleType>

    <simpleType name="VendorCode">
        <restriction base="ID">
            <pattern value="[A-Z]\d{5}"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="seed"/>
            <enumeration value="leaf"/>
            <enumeration value="cutting"/>
        </restriction>
    </simpleType>

    <simpleType name="PotType">
        <restriction base="string">
            <enumeration value="solid"/>
            <enumeration value="drainage"/>
            <enumeration value="pot-holder"/>
        </restriction>
    </simpleType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="turf"/>
            <enumeration value="soddy-podzolic"/>
            <enumeration value="humus"/>
        </restriction>
    </simpleType>

    <simpleType name="BudState">
        <restriction base="string">
            <enumeration value="open"/>
            <enumeration value="half_open"/>
            <enumeration value="closed"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <enumeration value="Europe"/>
            <enumeration value="Asia"/>
            <enumeration value="Africa"/>
            <enumeration value="South_America"/>
            <enumeration value="North_America"/>
            <enumeration value="Australia"/>
        </restriction>
    </simpleType>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="red"/>
            <enumeration value="white"/>
            <enumeration value="yellow"/>
            <enumeration value="blue"/>
            <enumeration value="pink"/>
        </restriction>
    </simpleType>
</schema>

=== KotofeyG/Task2/test_resources/data/invalidFlowerData.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:com.kotov.greenhouse"
         xsi:schemaLocation="urn:com.kotov.greenhouse ../schema/testSchema.xsd">

    <cut-flower vendor-code="A00001" planting-date="2020-02-01" cut-date="2021-04-27">
        <title>Rosa Aida @</title>
        <origin>Europe</origin>
        <petal-color>pink</petal-color>
        <stem-length>70</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00002" planting-date="2020-05-10" cut-date="2021-04-27" leaves="false">
        <title>Rosa Duftwolke </title>
        <origin>Europe</origin>
        <petal-color>red</petal-color>
        <stem-length>72</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00003" planting-date="2019-07-09" cut-date="2021-04-27">
        <title>Rosa Captain Harry Stebbings</title>
        <origin>North_America</origin>
        <petal-color>red</petal-color>
        <stem-length>60</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00004" planting-date="2020-07-25" cut-date="2021-04-27" leaves="false">
        <title>Rosa Miss All American Beauty</title>
        <origin>North_America</origin>
        <petal-color>white</petal-color>
        <stem-length>75</stem-length>
        <bud-state>closed</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00005" planting-date="2019-03-25" cut-date="2021-04-27" leaves="false">
        <title>Tulip Yellow Jewel</title>
        <origin>Europe</origin>
        <petal-color>yellow</petal-color>
        <stem-length>60</stem-length>
        <bud-state>closed</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00006" planting-date="2020-05-03" cut-date="2021-04-27">
        <title>Tulip Cape Town</title>
        <origin>Europe</origin>
        <petal-color>yellow</petal-color>
        <stem-length>50</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00007" planting-date="2020-07-06" cut-date="2021-04-27" leaves="false">
        <title>Lily Cassandra</title>
        <origin>Asia</origin>
        <petal-color>white</petal-color>
        <stem-length>40</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00008" planting-date="2020-08-10" cut-date="2021-04-27">
        <title>Lily Dizzy</title>
        <origin>Europe</origin>
        <petal-color>pink</petal-color>
        <stem-length>60</stem-length>
        <bud-state>closed</bud-state>
    </cut-flower>
    <indoor-flower vendor-code="B00001" planting-date="2017-01-10">
        <title>Anigozanthos</title>
        <origin>Australia</origin>
        <petal-color>red</petal-color>
        <pot-type>solid</pot-type>
        <soil>turf</soil>
        <watering>1200</watering>
        <average-temperature>25</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00002" planting-date="2016-12-30">
        <title>Hippeastrum</title>
        <origin>South_America</origin>
        <petal-color>pink</petal-color>
        <pot-type>drainage</pot-type>
        <soil>humus</soil>
        <watering>750</watering>
        <average-temperature>22</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00003" planting-date="2017-06-08">
        <title>Viola odorata</title>
        <origin>Asia</origin>
        <petal-color>blue</petal-color>
        <pot-type>solid</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>350</watering>
        <average-temperature>21</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00004" planting-date="2018-11-21">
        <title>Hypoestes</title>
        <origin>Africa</origin>
        <petal-color>blue</petal-color>
        <pot-type>pot-holder</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>650</watering>
        <average-temperature>25</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00005" planting-date="2015-05-05">
        <title>Adenium</title>
        <origin>Africa</origin>
        <petal-color>red</petal-color>
        <pot-type>drainage</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>500</watering>
        <average-temperature>25</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>cutting</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00006" planting-date="2016-01-28">
        <title>Calla</title>
        <origin>Africa</origin>
        <petal-color>white</petal-color>
        <pot-type>drainage</pot-type>
        <soil>turf</soil>
        <watering>300</watering>
        <average-temperature>26</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00007" planting-date="2021-03-10">
        <title>Lantana</title>
        <origin>South_America</origin>
        <petal-color>yellow</petal-color>
        <pot-type>pot-holder</pot-type>
        <soil>humus</soil>
        <watering>450</watering>
        <average-temperature>23</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00008" planting-date="2020-04-13">
        <title>Thunbergia</title>
        <origin>Africa</origin>
        <petal-color>white</petal-color>
        <pot-type>solid</pot-type>
        <soil>turf</soil>
        <watering>800</watering>
        <average-temperature>24</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>cutting</multiplying>
    </indoor-flower>
</flowers>

=== KotofeyG/Task2/test_resources/data/testFlowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:com.kotov.greenhouse"
         xsi:schemaLocation="urn:com.kotov.greenhouse ../schema/testSchema.xsd">

    <cut-flower vendor-code="A00002" planting-date="2001-02-09" cut-date="2002-04-11" leaves="false">
        <title>CutFlowerKL</title>
        <origin>Africa</origin>
        <petal-color>yellow</petal-color>
        <stem-length>33</stem-length>
        <bud-state>closed</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00000" planting-date="2001-02-03" cut-date="2002-04-05" leaves="false">
        <title>CutFlower</title>
        <origin>Europe</origin>
        <petal-color>red</petal-color>
        <stem-length>30</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00006" planting-date="2001-03-17" cut-date="2002-05-17" leaves="false">
        <title>CutFlowerKLMNOP</title>
        <origin>Asia</origin>
        <petal-color>yellow</petal-color>
        <stem-length>51</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00001" planting-date="2001-02-05" cut-date="2002-04-07">
        <title>CutFlowerK</title>
        <origin>Asia</origin>
        <petal-color>white</petal-color>
        <stem-length>31</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00004" planting-date="2001-02-23" cut-date="2002-04-25" leaves="false">
        <title>CutFlowerKLMN</title>
        <origin>North_America</origin>
        <petal-color>pink</petal-color>
        <stem-length>40</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00003" planting-date="2001-02-15" cut-date="2002-04-17">
        <title>CutFlowerKLM</title>
        <origin>South_America</origin>
        <petal-color>blue</petal-color>
        <stem-length>36</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00007" planting-date="2001-03-31" cut-date="2002-05-31">
        <title>CutFlowerKLMNOPQ</title>
        <origin>Africa</origin>
        <petal-color>blue</petal-color>
        <stem-length>58</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00005" planting-date="2001-03-05" cut-date="2002-05-05">
        <title>CutFlowerKLMNO</title>
        <origin>Australia</origin>
        <petal-color>white</petal-color>
        <stem-length>45</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <indoor-flower vendor-code="B00003" planting-date="2001-02-21">
        <title>IndoorFlowerABC</title>
        <origin>South_America</origin>
        <petal-color>blue</petal-color>
        <pot-type>solid</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>450</watering>
        <average-temperature>22.5</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00000" planting-date="2003-06-07">
        <title>IndoorFlower</title>
        <origin>Asia</origin>
        <petal-color>white</petal-color>
        <pot-type>pot-holder</pot-type>
        <soil>turf</soil>
        <watering>300</watering>
        <average-temperature>15</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00005" planting-date="2001-03-15">
        <title>IndoorFlowerABCDE</title>
        <origin>Australia</origin>
        <petal-color>white</petal-color>
        <pot-type>solid</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>550</watering>
        <average-temperature>27.5</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00007" planting-date="2001-04-14">
        <title>IndoorFlowerABCDEFG</title>
        <origin>Africa</origin>
        <petal-color>blue</petal-color>
        <pot-type>solid</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>650</watering>
        <average-temperature>32.5</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00002" planting-date="2001-02-13">
        <title>IndoorFlowerAB</title>
        <origin>Africa</origin>
        <petal-color>yellow</petal-color>
        <pot-type>drainage</pot-type>
        <soil>humus</soil>
        <watering>400</watering>
        <average-temperature>20</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>cutting</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00001" planting-date="2001-02-07">
        <title>IndoorFlowerA</title>
        <origin>Asia</origin>
        <petal-color>white</petal-color>
        <pot-type>solid</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>350</watering>
        <average-temperature>17.5</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00006" planting-date="2001-03-29">
        <title>IndoorFlowerABCDEF</title>
        <origin>Asia</origin>
        <petal-color>yellow</petal-color>
        <pot-type>pot-holder</pot-type>
        <soil>turf</soil>
        <watering>600</watering>
        <average-temperature>30</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00004" planting-date="2001-03-03">
        <title>IndoorFlowerABCD</title>
        <origin>North_America</origin>
        <petal-color>pink</petal-color>
        <pot-type>pot-holder</pot-type>
        <soil>turf</soil>
        <watering>500</watering>
        <average-temperature>25</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
</flowers>

=== KotofeyG/Task2/test_resources/testFlowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:com.kotov.greenhouse"
         xsi:schemaLocation="urn:com.kotov.greenhouse testSchema.xsd">

    <cut-flower vendor-code="A00001" planting-date="2020-02-01" cut-date="2021-04-27">
        <title>Rosa Aida</title>
        <origin>Europe</origin>
        <petal-color>pink</petal-color>
        <stem-length>70</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00002" planting-date="2020-05-10" cut-date="2021-04-27" leaves="false">
        <title>Rosa Duftwolke</title>
        <origin>Europe</origin>
        <petal-color>red</petal-color>
        <stem-length>72</stem-length>
        <bud-state>half_open</bud-state>
    </cut-flower>
    <cut-flower vendor-code="A00003" planting-date="2019-07-09" cut-date="2021-04-27">
        <title>Rosa Captain Harry Stebbings</title>
        <origin>North_America</origin>
        <petal-color>red</petal-color>
        <stem-length>60</stem-length>
        <bud-state>open</bud-state>
    </cut-flower>
    <indoor-flower vendor-code="B00001" planting-date="2017-01-10">
        <title>Anigozanthos</title>
        <origin>Australia</origin>
        <petal-color>red</petal-color>
        <pot-type>solid</pot-type>
        <soil>turf</soil>
        <watering>1200</watering>
        <average-temperature>25</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00002" planting-date="2016-12-30">
        <title>Hippeastrum</title>
        <origin>South_America</origin>
        <petal-color>pink</petal-color>
        <pot-type>drainage</pot-type>
        <soil>humus</soil>
        <watering>750</watering>
        <average-temperature>22</average-temperature>
        <photophilous>true</photophilous>
        <multiplying>seed</multiplying>
    </indoor-flower>
    <indoor-flower vendor-code="B00003" planting-date="2017-06-08">
        <title>Viola odorata</title>
        <origin>Asia</origin>
        <petal-color>blue</petal-color>
        <pot-type>solid</pot-type>
        <soil>soddy-podzolic</soil>
        <watering>350</watering>
        <average-temperature>21</average-temperature>
        <photophilous>false</photophilous>
        <multiplying>leaf</multiplying>
    </indoor-flower>
</flowers>
